language: ruby
services:
  - postgresql
before_script:
  - psql -c 'create database operationcode_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:migrate
  - RAILS_ENV=test bundle exec rake db:test:prepare
